# Header items
menu:
  主页:
    url: /
    image: https://i.loli.net/2020/10/27/YKoBd2uCMcxp4ZE.jpg
    title: 主页
  博客存档:
    url: /archives/
    title: 所有博客
avatar: /imgs/avatar-s.png

archives:
  seasonImage:
    spring: 
    summer: 
    autumn: 
    winter: 

# Social Accounts
accounts:
  github:
  zhihu:
  weibo:
  lofter:
  gitee:

# Widgets
useLive2d: true
live2d:
  #model: /model/Kobayaxi/Kobayaxi.model.json
  model: /model/senko/senko.model3.json